# permissions for end users to edit ok3sconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ok3sconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: okr
    app.kubernetes.io/part-of: okr
    app.kubernetes.io/managed-by: kustomize
  name: ok3sconfig-editor-role
rules:
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - ok3sconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - ok3sconfigs/status
  verbs:
  - get
